"""Added image_url to Recipe Model

Revision ID: 6904bd4a0aa5
Revises: 618535acb298
Create Date: 2023-05-12 16:19:42.955031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6904bd4a0aa5'
down_revision = '618535acb298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
